dist: bionic

language: python

python: '3.12'

install: pipenv install --dev

services:
  - docker

if: type != push OR branch = latest

jobs:
  include:
    - stage: Build, Test and Publish
      name: Testrun crawler
      script: pipenv run ./crawler.py --region Utrecht

    - stage: Build, Test and Publish
      name: Linting
      script: pipenv run black ./ --line-length 120 --check --diff

    - stage: Build, Test and Publish
      name: Build and publish image
      if: branch = latest AND type != pull_request
      install: docker pull nstapelbroek/estate-crawler:latest
      script: printenv DOCKERHUB_PASSWORD | docker login --username nstapelbroekbot --password-stdin && docker tag nstapelbroek/estate-crawler:$TRAVIS_BRANCH docker.io/nstapelbroek/estate-crawler:$TRAVIS_BRANCH && docker push docker.io/nstapelbroek/estate-crawler

  allow_failures:
    - stage: Build, Test and Publish
      name: Security checks
      script: pipenv check --system
