sudo: false

language: python

install: pip install --upgrade pip && python -m pip install https://github.com/pypa/pipenv/archive/7745e51a63cbd17c7ba9ef9f75ec974f8b5543d1.tar.gz

services:
  - docker

jobs:
  include:
    - stage: Build image
      if: type = pull_request
      install: docker pull nstapelbroek/estate-crawler:latest
      script: make validate-pr
    - stage: Build and publish image
      if: branch = latest AND type != pull_request
      install: make validate
      script: docker run --rm -it --name my-crawler-instance -v $(pwd):/app/build nstapelbroek/estate-crawler --region amsterdam
      after_success:  printenv DOCKERHUB_PASSWORD | docker login --username nstapelbroekbot --password-stdin && docker tag nstapelbroek/estate-crawler:$TRAVIS_BRANCH docker.io/nstapelbroek/estate-crawler:$TRAVIS_BRANCH && docker push docker.io/nstapelbroek/estate-crawler

    - stage: Test run
      script:
        - pipenv run ./crawler.py --region Utrecht
      python: '3.6'
    - stage: Test run
      script:
        - pipenv run ./crawler.py --region Utrecht
      python: '3.7'
      dist: xenial
      sudo: true
