dist: focal

language: python

python: '3.9'

install: pipenv install --dev

services:
  - docker

jobs:
  include:
    - stage: Build, Test and Publish
      script: pipenv run ./crawler.py --region Utrecht

    - stage: Build, Test and Publish
      if: type = pull_request
      install: docker pull nstapelbroek/estate-crawler:latest
      script: make validate-pr

    - stage: Build, Test and Publish
      if: branch = latest AND type != pull_request
      install: make validate
      script: docker run --rm -it --name my-crawler-instance -v $(pwd):/app/build nstapelbroek/estate-crawler --region amsterdam
      after_success:  printenv DOCKERHUB_PASSWORD | docker login --username nstapelbroekbot --password-stdin && docker tag nstapelbroek/estate-crawler:$TRAVIS_BRANCH docker.io/nstapelbroek/estate-crawler:$TRAVIS_BRANCH && docker push docker.io/nstapelbroek/estate-crawler
